apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: fadeleafj/orders
          env:
            - name: NATSURL
              value: 'http://nats-srv:4222'
            - name: NATSCLUSTERID
              value: 'ticketing'
            - name: NATSCLIENTID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGOURI
              value: 'mongodb://orders-mongo-srv:27017/orders'
            - name: JWTKEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWTKEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
